package com.extension.leetcodeSolutionExplaination.services;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.Base64;
import java.util.HashMap;
import java.util.Map;

@Slf4j
@Service
@RequiredArgsConstructor
public class GitHubService {

    private static final String GITHUB_API = "https://api.github.com";
    private static final String REPO_NAME  = "leetcode-solution-explanations";

    private final RestTemplate restTemplate;

    // ─── Create repo if it doesn't exist ───────────────────────────────────
    public void ensureRepoExists(String token, String username) {
        String url = GITHUB_API + "/repos/" + username + "/" + REPO_NAME;
        HttpHeaders headers = buildHeaders(token);

        try {
            restTemplate.exchange(url, HttpMethod.GET, new HttpEntity<>(headers), String.class);
            log.info("Repo already exists: {}", REPO_NAME);
        } catch (Exception e) {
            log.info("Repo not found, creating: {}", REPO_NAME);
            createRepo(token);
        }
    }

    // ─── Push .md file to repo ──────────────────────────────────────────────
    public void pushExplanation(String token, String username,
                                String problemName, String content) {
        ensureRepoExists(token, username);

        String fileName = sanitizeFileName(problemName) + ".md";
        String url = GITHUB_API + "/repos/" + username + "/" + REPO_NAME + "/contents/" + fileName;
        HttpHeaders headers = buildHeaders(token);

        // Check if file already exists (get its SHA for update)
        String sha = getFileSha(url, headers);

        String encodedContent = Base64.getEncoder().encodeToString(content.getBytes());

        Map<String, String> body = new HashMap<>();
        body.put("message", sha == null
                ? "Add explanation: " + problemName
                : "Update explanation: " + problemName);
        body.put("content", encodedContent);
        if (sha != null) body.put("sha", sha); // required for update

        HttpEntity<Map<String, String>> request = new HttpEntity<>(body, headers);
        restTemplate.exchange(url, HttpMethod.PUT, request, String.class);
        log.info("Successfully pushed: {}", fileName);
    }

    // ─── Get GitHub username from token ────────────────────────────────────
    public String getUsername(String token) {
        String url = GITHUB_API + "/user";
        HttpHeaders headers = buildHeaders(token);
        ResponseEntity<Map> response = restTemplate.exchange(
                url, HttpMethod.GET, new HttpEntity<>(headers), Map.class);
        return (String) response.getBody().get("login");
    }

    // ─── Private helpers ────────────────────────────────────────────────────
    private void createRepo(String token) {
        String url = GITHUB_API + "/user/repos";
        HttpHeaders headers = buildHeaders(token);

        Map<String, Object> body = new HashMap<>();
        body.put("name", REPO_NAME);
        body.put("description", "LeetCode solution explanations generated by AI");
        body.put("private", false);
        body.put("auto_init", true); // creates README.md so repo is not empty

        restTemplate.exchange(url, HttpMethod.POST,
                new HttpEntity<>(body, headers), String.class);
    }

    private String getFileSha(String url, HttpHeaders headers) {
        try {
            ResponseEntity<Map> response = restTemplate.exchange(
                    url, HttpMethod.GET, new HttpEntity<>(headers), Map.class);
            return (String) response.getBody().get("sha");
        } catch (Exception e) {
            return null; // file doesn't exist yet
        }
    }

    private HttpHeaders buildHeaders(String token) {
        HttpHeaders headers = new HttpHeaders();
        headers.set("Authorization", "Bearer " + token);
        headers.set("Accept", "application/vnd.github+json");
        headers.set("X-GitHub-Api-Version", "2022-11-28");
        headers.setContentType(MediaType.APPLICATION_JSON);
        return headers;
    }

    private String sanitizeFileName(String name) {
        return name.toLowerCase()
                .trim()
                .replaceAll("[^a-z0-9\\s-]", "")
                .replaceAll("\\s+", "-");
    }
}
