spring.application.name=leetcodeSolutionExplaination

# Port
server.port=8081

# spring-ai-starter-model-google-genai API KEY
spring.ai.google.genai.api-key=AIzaSyAoS-fgTS4vSzh36jS8UySyy0TvC3jZl-M

# Updated model — gemini-1.5-flash is deprecated, using gemini-2.0-flash
spring.ai.google.genai.chat.options.model=gemini-2.5-flash